---
slug: vr
filename: vr
title: Beginner's Guide to Virtual Reality Development
subtitle: Start Building Your World Now
description: Change me.
author: Mark Maximus Muskardin
copyright: 2014
uuid: 07078ffa-9e00-4628-9b25-758524e0ee2e
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
